# Generated by Django 3.0.3 on 2020-03-09 17:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20200306_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='tagged_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
