# Generated by Django 3.0.3 on 2020-03-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
